spring:
  data:
    redis:
      port: 6380
      host: localhost
      ttl: 7d

  profiles:
    active: prod

server:
  port: 9010

user-service:
  host: localhost
  port: 9000

event-service:
  host: localhost
  port: 9005

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v1/api-docs
  default-produces-media-type: application/json

news-feed:
  count-in-cache: 500
  count: 10

thread-pool-size:
  event-save: 10